Modified db and web to be able to use external site configs.
Each site will be in it's own directory at the same level as this one
(i.e. a sibling of the top level directory of this distribution). This
is because each site will be in its own separate git repository.

To use, simply pass the name to the db or web script as the third
argument.

diff --git a/db b/db
--- a/db
+++ b/db
@@ -7,13 +7,22 @@ cd $(dirname $0)
 
 source config.sh
 
-if [ ! -z "$2" ]; then
-	source $2/config.sh
+if [ -z "$2" ]; then
+	export SITENAME=default
+else
+	export SITENAME=$2
 fi
 
-if [ -z "$SITENAME" ]; then
-	source default/config.sh
+if [ -d "$SITENAME" ]; then
+	export SITEPATH=$SITENAME
+elif [ -d "../$SITENAME" ]; then
+	export SITEPATH="../$SITENAME"
+else
+	echo "Cannot find $SITENAME directory here or in ../$SITENAME"
+	exit 1
 fi
+
+source $SITEPATH/config.sh
 
 PGSTOP="$PGBIN/pg_ctl -w stop -D $PGDATA"
 PGSTART="$PGBIN/pg_ctl -w start -D $PGDATA -l $SITEROOT/logs/postgres.log"
diff --git a/web b/web
--- a/web
+++ b/web
@@ -7,23 +7,32 @@ cd $(dirname $0)
 
 source config.sh
 
-if [ ! -z "$2" ]; then
-	source $2/config.sh
+if [ -z "$2" ]; then
+	export SITENAME=default
+else
+	export SITENAME=$2
 fi
 
-if [ -z "$SITENAME" ]; then
-	source default/config.sh
+if [ -d "$SITENAME" ]; then
+	export SITEPATH=$SITENAME
+elif [ -d "../$SITENAME" ]; then
+	export SITEPATH="../$SITENAME"
+else
+	echo "Cannot find $SITENAME directory here or in ../$SITENAME"
+	exit 1
 fi
+
+source $SITEPATH/config.sh
 
 case $1 in
 	start)
 		if [ ! -L "$NSROOT/servers/$SITENAME" ]; then
 			/bin/rm -rf $NSROOT/servers/$SITENAME
-			/bin/ln -s $SITEROOT/$SITENAME $NSROOT/servers
+			/bin/ln -s $SITEPATH $NSROOT/servers
 		fi
 		$NSROOT/bin/nsd \
 			$NS_DEBUG \
-			-t $SITEROOT/$SITENAME/nsd.tcl \
+			-t $SITEPATH/nsd.tcl \
 			-u $SITEOWNER \
 			-g $SITEGROUP \
 			-s $SITENAME \
